source 'https://rubygems.org'

gem 'colorize'
gem 'launchy'
gem 'httparty'
gem 'nokogiri'
gem 'json'
gem 'rspec'
gem 'rubocop', '~>0.81.0'
gem 'terminal-basic-menu'
gem 'terminal-table'
gem 'byebug'
gem 'watir'
gem 'webdrivers'
gem 'pry'