source 'https://rubygems.org'

gem 'byebug'
gem 'colorize'
gem 'httparty'
gem 'json'
gem 'launchy'
gem 'nokogiri'
gem 'pry'
gem 'rspec'
gem 'rubocop', '>= 1.0', '< 2.0'
gem 'terminal-basic-menu'
gem 'terminal-table'
gem 'watir'
gem 'webdrivers'
